// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drhdcqwgslwzxyvsfeha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyaGRjcXdnc2x3enh5dnNmZWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTYxNDUsImV4cCI6MjA2NTI3MjE0NX0.rMtxADS1AQmHDoqYdkwdkoVZ6ift4Y1iL352gOgAKhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);